name: CI
on: push

jobs:
  checks:
    name: Code Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install nasm
        run: sudo apt-get install -y nasm
      - name: Configure code
        run: cmake -B bin -DRS_WARN_ERROR=ON
      - name: Build code
        run: make -C bin VERBOSE=1
      - name: Format code
        run: make -C bin clang-format
      - name: Check formatting and ignores
        run: git diff --color --exit-code
