name: CI
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install -y ninja-build libavutil-dev libavformat-dev libavdevice-dev libavcodec-dev libswscale-dev libx11-dev libunwind-dev
      - run: python3 -m pip install -U pip setuptools
      - run: python3 -m pip install meson
      - run: meson bin --buildtype release -Dx11_gpl=true
      - run: ninja -C bin
